// <auto-generated />
namespace QuickOrderAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcreateTimeandUpdateTimeinthebaseEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreateTimeandUpdateTimeinthebaseEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291504268_add createTime and UpdateTime in the base Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
